# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Jabuke sa Peska
email: ''
address: Kovács János 6782
phone_number: 00+381 24 882-230
description: >
  Jabuke sa Peska.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://127.0.0.1" # the base hostname & protocol for your site
facebook_name: kinallat

# Build settings
markdown: kramdown
